# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions
name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: |
          echo "Imprimindo todas as variáveis do github"
          echo "${{ toJSON(github) }}" # Imprime todas as variáveis de ambiente possíveis do Github
      
      - name: Output Github Env
        run: | 
          echo "Imprimindo a variável de ambiente"
          echo "${{ toJson(github.env) }}" # Imprime apenas a variável de ambiente