name: Unit test

on: 
  push  # Será disparado sempre que um push ocorrer

jobs: 
  unit-test:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3 # GitHub Action used in workflows to check out your repository's code so subsequent steps in the workflow can access the files in it. It is like a download of the files.

      - name: Begin
        run: echo "Beginning unit tests on main.py"

      - name: Set up Python
        uses: actions/setup-python@v4 # Instalar a linguagem que se deseja usar. Neste caso, python
        with:
          python-version: '3.10'  # or any version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover python/tests/
          coverage report